name: amplicon-environment
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - r-base=4.5.1
  - r-biocmanager
  - r-dendextend
  - r-devtools
  - r-fpc
  - r-mvtnorm
  - r-reshape
  - r-tidyr
  - r-vegan
  - r-viridis
  - pip
  - pip:
    - cutadapt
    - matplotlib
