name: amplicon-environment
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - psutil
  - toolz
  - dill
  - partd
  - bokeh
  - dask
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
