name: amplicon-environment
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - r-base
  - r-biocmanager
  - r-dendextend
  - r-devtools
  - r-fpc
  - r-mvtnorm
  - r-reshape
  - r-tidyr
  - r-vegan
  - r-viridis
  - rstudio-desktop
  - pip
  - pip:
    - cutadapt
    - matplotlib
